parser: main.c scan.c tree.c expr.c interp.c 
				cc -o parser -g main.c scan.c tree.c expr.c interp.c

# scanner: main.cpp Scanner.cpp Scanner.h
# 			g++ -g -o scanner main.cpp Scanner.cpp Scanner.h
clean: 
		rm -rf parser *.o
